import { Map, Sidebar } from 'components';
import type { NextPage } from 'next';
import Head from 'next/head';
import { MapProvider } from 'providers';

const Home: NextPage = () => {
  return (
    <MapProvider>
      <div className='h-screen overflow-hidden'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Map />
      </div>
      <Sidebar />
    </MapProvider>
  );
};

export default Home;
