import { Map } from 'components';
import type { NextPage } from 'next';
import Head from 'next/head';
import { MapProvider } from 'providers';
import { MapItem } from 'types/map';
import { v4 as UUID } from 'uuid';

const data: MapItem[] = [
  { id: UUID(), top: 1, left: 1, size: 2 },
  { id: UUID(), top: 3, left: 1, size: 1 },
  { id: UUID(), top: 5, left: 1, size: 1 },
  { id: UUID(), top: 6, left: 2, size: 1 },
  { id: UUID(), top: 3, left: 3, size: 3 },
  { id: UUID(), top: 8, left: 2, size: 4 },
];

const Home: NextPage = () => {
  return (
    <MapProvider>
      <div className='h-screen overflow-hidden'>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Map data={data} />
      </div>
    </MapProvider>
  );
};

export default Home;
